platform :ios, '7.0'

pod 'MagicalRecord', '~> 2.2'
pod 'InAppSettingsKit', '~> 2.0.1'
pod 'CocoaSoundCloudAPI', '~> 1.0.2'
pod 'CocoaSoundCloudUI', '~> 1.0.9'
pod 'XCDYouTubeKit', '~> 2.0.0'
pod 'AFNetworking', '~> 2.2.4'
pod 'TMCache', '~> 1.2.0'
pod 'SWRevealViewController', '~> 1.1.1'
pod 'MSLabel', '~> 0.0.1'
pod 'LEColorPicker', '~> 1.0.2'
pod 'FXBlurView', '~> 1.5.3'
pod 'Parse', '~> 1.2.19'
pod 'HockeySDK', '~> 3.5.5'
pod 'CrashlyticsFramework', '~> 2.1.9'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.7'